import type { Request, Response, NextFunction, ErrorRequestHandler } from 'express';
import loggerProvider from '../logger/loggerProvider';

function errorLogger(): ErrorRequestHandler {
  const logger = loggerProvider.getLogger();

  return (err: Error | any, req: Request, res: Response, next: NextFunction): void => {
    const log = err instanceof Error
      ? {
          error_name: err.name,
          error_message: err.message,
          error_stack: err.stack,
        }
      : { error_message: String(err) };

    const context = {
      request_url: req.originalUrl || req.url,
      request_method: req.method,
      request_id: req.id, // Generated by pino-http
      client_ip: req.ip,
      user_agent: req.get('user-agent'),
      content_type: req.get('content-type'),
      status_code: res.statusCode,
    };

    if (res.statusCode >= 500) {
      logger.error({ ...log, ...context }, 'Application error occurred');
    } else {
      logger.warn({ ...log, ...context }, 'Application warning occurred');
    }

    next(err);
  };
}

export default errorLogger;
