version: '3.8'
services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile.production
      target: prod
    ports:
      - '80:80'
    container_name: trofos-frontend-production
    restart: always
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.production
      target: prod
    ports:
      - '3001:3001'
    container_name: trofos-backend-production
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/trofos?schema=public
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
