# This Dockerfile is to simulate how deployed servers run the 
# application, but you build the images locally. Frontend has
# a different Dockerfile to simulate the reverse proxy forwarding
# api traffic to backend
version: '3.8'

networks:
  application:
    driver: bridge
    name: trofos-application

services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: ./local_dev_docker/Dockerfile.dev
      target: prod
    ports:
      - '3000:80'
    container_name: trofos-frontend-production
    restart: always
    links:
      - backend
    networks:
      - application
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.production
      target: prod
    ports:
      - '3001:3001'
    container_name: trofos-backend-production
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - NODE_ENV=${NODE_ENV}
      - EMAIL_SERVICE=${EMAIL_SERVICE}
      - AWS_SES_FROM_EMAIL=${AWS_SES_FROM_EMAIL}
    links:
      - postgres
    networks:
      - application
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - application
volumes:
  postgres:
