# This Dockerfile is to simulate how deployed servers run the
# application, but you build the images locally. Frontend has
# a different Dockerfile to simulate the reverse proxy forwarding
# api traffic to backend
version: '3.8'

networks:
  application:
    driver: bridge
    name: trofos-application

services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: ./local_dev_docker/Dockerfile.dev
      target: prod
    ports:
      - '3000:80'
    container_name: trofos-frontend-production
    restart: always
    links:
      - backend
    networks:
      - application
  api_gateway:
    build:
      context: ./packages/api_gateway
      dockerfile: Dockerfile
    ports:
      - '3001:80'
    container_name: trofos-api-gateway-production
    restart: always
    networks:
      - application
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.production
      target: prod
    ports:
      - '3003:3003'
    container_name: trofos-backend-production
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_BASE_URL=${FRONTEND_BASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - EMAIL_KEY=${EMAIL_KEY}
      - NODE_ENV=${NODE_ENV}
      - AWS_SES_FROM_EMAIL=${AWS_SES_FROM_EMAIL}
      - SP_PRIVATE_KEY_BASE64=${SP_PRIVATE_KEY_BASE64}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_DATABASE_URL=${AI_DATABASE_URL}
    links:
      - postgres
    networks:
      - application
  hocus_pocus_server:
    build:
      context: ./packages/hocus_pocus_server
      dockerfile: Dockerfile.production
      target: prod
    ports:
      - '3002:3002'
    container_name: trofos-hocus-pocus-server-production
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BACKEND_URL=${BACKEND_URL}
    networks:
      - application
  postgres:
    image: pgvector/pgvector:pg14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - application
volumes:
  postgres:
