version: '3.8'
services:
  frontend:
    build: 
      context: ./packages/frontend
      dockerfile: Dockerfile.production
    ports:
      - "3000:3000"
    container_name: trofos-frontend-production
    restart: always
    links:
      - backend
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile.production
    ports:
      - "3001:3001"
    container_name: trofos-backend-production
    restart: always
    links:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
