import React, { useState } from 'react';
import { Button, Form, Modal, Tooltip, message } from 'antd';
import { useParams } from 'react-router-dom';
import { useAddBacklogsMutation } from '../../api/socket/backlogHooks';
import BacklogUserSelect from '../fields/BacklogUserSelect';
import BacklogTextArea from '../fields/BacklogTextArea';
import type { BacklogSelectTypes, BacklogFormFields } from '../../helpers/BacklogModal.types';
import './BacklogCreationModal.css';
import { useGetProjectQuery } from '../../api/project';
import { Sprint, useGetSprintsByProjectIdQuery } from '../../api/sprint';
import { DefaultBacklog, Retrospective } from '../../api/types';
import { useGetEpicsByProjectIdQuery } from '../../api/backlog';
import { getErrorMessage } from '../../helpers/error';
import { GENERIC_NEW_SPRINT, autoSuggestNewSprint } from '../../helpers/sprintCreationHelper';
import { STEP_PROP, StepTarget } from '../tour/TourSteps';
import { useGetUserInfoQuery } from '../../api/auth';

function BulkBacklogCreationModal({
  fixedSprint,
  title,
  modalKey,
  defaultBacklog,
  disabled,
  retrospective,
  disableClickEvent,
}: {
  fixedSprint?: Sprint;
  title?: string;
  modalKey?: string | number;
  defaultBacklog?: DefaultBacklog;
  disabled?: boolean;
  retrospective?: Retrospective;
  disableClickEvent?: boolean;
}): JSX.Element {

  const params = useParams();
  const [form] = Form.useForm();

  const projectId = Number(params.projectId);

  const [addBacklogs] = useAddBacklogsMutation();
  const { data: projectData } = useGetProjectQuery({ id: projectId });
  const { data: epicData } = useGetEpicsByProjectIdQuery({ projectId: projectId });
  const { data: projectSprintData } = useGetSprintsByProjectIdQuery(projectId);

  const [isModalVisible, setIsModalVisible] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [isSprintModalVisible, setIsSprintModalVisible] = useState(false);
  const [newSprint, setNewSprint] = useState<Sprint | undefined>(undefined);
  const { data: userInfo } = useGetUserInfoQuery();

  const showModal = () => {
    setIsModalVisible(true);
  };

  const handleOk = () => {
    setIsModalVisible(false);
  };

  const handleCancel = () => {
    setIsModalVisible(false);
  };

  const handleFormSubmit = async (data: {reporterId: number, prompt: string}): Promise<void> => {
    setIsLoading(true);

    console.log(data);

    const payload = {
      ...data,
      projectId: Number(params.projectId),
    };

    try {
      await addBacklogs(payload).unwrap();
      setIsModalVisible(false);
      form.resetFields();
      message.success('Backlogs created successfully');
    } catch (e) {
      console.error(e);
      message.error(getErrorMessage(e));
    } finally {
      setIsLoading(false);
    }
  };

  const renderFooter = (): JSX.Element[] => [
    <Button
      form={`newBacklogs${modalKey ? `-${modalKey}` : ''}`}
      key="submit"
      type="primary"
      htmlType="submit"
      loading={isLoading}
    >
      Create
    </Button>,
  ];

  // Sort sprints by ID desc
  let sprintOptionsDescending = projectSprintData?.sprints
    ? projectSprintData.sprints
        .map((sprint) => {
          // If there is a retrospective, let user know what sprint it is for
          if (retrospective && sprint.id === retrospective.sprint_id) {
            return { id: sprint.id, name: `${sprint.name} (This retrospective)` };
          }
          return { id: sprint.id, name: sprint.name };
        })
        .sort((a, b) => b.id - a.id)
    : [];

  // If most recent sprint == retrospective sprint and no active sprint, prompt user to create a new sprint
  const shouldCreateNewSprint =
    retrospective &&
    sprintOptionsDescending[0]?.id === retrospective.sprint_id &&
    !projectSprintData?.sprints?.find((s) => s.status === 'current');

  const autoGeneratedNewSprint =
    projectSprintData?.sprints && projectSprintData.sprints.length > 0
      ? autoSuggestNewSprint(projectSprintData.sprints[projectSprintData.sprints.length - 1])
      : GENERIC_NEW_SPRINT;

  const renderReporterSelect = (): JSX.Element => {
    //todo
    console.log(defaultBacklog);
    const defaultReporter = defaultBacklog?.reporter_id ?? undefined;
    return (
      <Form.Item name="reporterId" label="Reporter" rules={[{ required: true }]} initialValue={defaultReporter}>
        <BacklogUserSelect options={projectData?.users || []} placeholder="Select User" />
      </Form.Item>
    );
  };

  const renderContent = (): JSX.Element => (
    <Form id={`newBacklogs${modalKey ? `-${modalKey}` : ''}`} form={form} onFinish={handleFormSubmit}>
      {renderReporterSelect()}
      <Form.Item name="prompt">
        <BacklogTextArea placeholder="Type prompt here..." autoSize={{ minRows: 5, maxRows: 8 }} />
      </Form.Item>
    </Form>
  );

  return (
    <>
      {disabled ? (
        <Tooltip title={`Backlog has already been created for this action`}>
          <Button className="new-backlog-btn" type="primary" disabled={disabled}>
            {title ?? 'Create Many Backlogs'}
          </Button>
        </Tooltip>
      ) : (
        <Button
          className="new-backlog-btn"
          type="primary"
          onClick={disableClickEvent ? undefined : showModal}
        >
          {title ?? 'Create Many Backlogs'}
        </Button>
      )}
      <Modal
        title={title ?? 'Bulk Backlog Creation'}
        open={isModalVisible}
        onOk={handleOk}
        onCancel={handleCancel}
        footer={renderFooter()}
        width={600}
      >
        {renderContent()}
      </Modal>
    </>
  );
}

export default BulkBacklogCreationModal;
