{
 "title": "Nodejs Application External Request Response Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Number of 200 OK vs Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{route=~\"/api/external/.*\", code=~\"2.*\"}[1m]))",
     "legendFormat": "Valid requests"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{route=~\"/api/external/.*\", code!~\"2.*\"}[1m]))",
     "legendFormat": "Error requests"
    }
   ]
  },
  {
   "title": "Sum of Response Code Over Past Hour",
   "type": "timeseries",
   "description": "Sum of 2XX, 4XX and 5XX response codes over past hour",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{route=~\"/api/external/.*\", code=~\"2.*\"}[1h]))",
     "legendFormat": "2xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{route=~\"/api/external/.*\", code=~\"4.*\"}[1h]))",
     "legendFormat": "4xx {{method}} {{route}}"
    },
    {
     "expr": "sum(increase(http_request_duration_ms_count{route=~\"/api/external/.*\", code=~\"5.*\"}[1m]))",
     "legendFormat": "5xx {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_ms_count{route=~\"/api/external/.*\"}[1m]))",
     "legendFormat": "Requests per minute"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(http_request_duration_ms_sum{route=~\"/api/external/.*\"}[$__range]) / rate(http_request_duration_ms_count{route=~\"/api/external/.*\"}[$__range])) by (route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th percentile response time for past 30m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_ms_bucket{route=~\"/api/external/.*\"}[1m])) by (le, route, method))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}