global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: 'trofos-backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend:3001']
  
  - job_name: 'postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['postgres-exporter:9187']
