apiVersion: 1
contactPoints:
    - orgId: 1
      name: telegram_bot_backend_restart
      receivers:
        - uid: de10c7jprtla9c
          type: telegram
          settings:
            bottoken: $GF_TELEGRAM_BOT_TOKEN
            chatid: "-4591565687" #TODO: put this into env variable when grafana merges fix https://github.com/grafana/grafana/issues/69950
            disable_notification: false
            disable_web_page_preview: false
            message: '{{ template "Generic alert template" . }}'
            protect_content: false
          disableResolveMessage: true
    - orgId: 1
      name: telegram_bot_general
      receivers:
        - uid: be10ja3y1kxkwc
          type: telegram
          settings:
            bottoken: $GF_TELEGRAM_BOT_TOKEN
            chatid: "-4591565687" # TODO: put in env var
            disable_notification: false
            disable_web_page_preview: false
            message: '{{ template "Generic alert template" . }}'
            protect_content: false
          disableResolveMessage: false

templates:
    - orgId: 1
      name: Generic alert template
      template: |
        {{ define "Generic alert template" }}
          {{ .Status }}: {{ .CommonAnnotations.summary }}
          
          {{.CommonAnnotations.description}}
        {{ end }}

policies:
    - orgId: 1
      receiver: telegram_bot_general
      group_by:
        - grafana_folder
        - alertname
      routes:
        - receiver: telegram_bot_backend_restart
          object_matchers:
            - - policy
              - =
              - Backend recently restarted
          group_interval: 2m
          repeat_interval: 2m
