name: E2E tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER_CI }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_CI }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB_CI }}
      E2E_DATABASE_URL: ${{ secrets.E2E_DATABASE_URL_CI }}
      E2E_AI_DATABASE_URL: ${{ secrets.E2E_AI_DATABASE_URL_CI }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'
          cache: 'pnpm'
      - name: Install wait-on
        run: pnpm i -g wait-on@6.0.1
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: packages/frontend
      - name: Set up application for E2E test
        run: docker compose -f ./docker-compose-e2e.yml up -d
      - name: Wait for backend to start
        run: npx wait-on --timeout 60000 http://127.0.0.1:3003
      - name: Seed db
        run: docker exec trofos-backend-production pnpm run prisma-migrate-reste --force
      - name: Run E2E tests
        run: pnpm exec playwright test --reporter=dot
        working-directory: packages/frontend
      - name: Stop Application
        if: always()
        run: docker compose -f ./docker-compose-e2e.yml down