name: CI Test for Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL_CI }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER_CI }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD_CI }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB_CI }}
      AI_DATABASE_URL: ${{ secrets.AI_DATABASE_URL_CI }}
      E2E_DATABASE_URL: ${{ secrets.E2E_DATABASE_URL_CI }}
      E2E_AI_DATABASE_URL: ${{ secrets.E2E_AI_DATABASE_URL_CI }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'
          cache: 'pnpm'
      - name: Install wait-on
        run: pnpm i -g wait-on@6.0.1
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
        working-directory: packages/frontend
      - name: Setup Postgres container
        run: pnpm run setup:ci
      - name: Build and test backend
        run: docker compose -f docker-compose-ci.yml build backend
      - name: Build and test frontend
        run: docker compose -f docker-compose-ci.yml build frontend
      - name: Build hocus pocus server
        run: docker compose -f docker-compose-ci.yml build hocus_pocus_server
      - name: Clean up container
        if: always()
        run: pnpm run cleanup:ci
      - name: Set up application for E2E test
        run: docker compose -f ./docker-compose-e2e.yml up -d
      - name: Wait for backend to start
        run: npx wait-on --timeout 60000 http://127.0.0.1:3003
      - name: Seed db
        run: docker exec trofos-backend-production pnpm exec prisma migrate reset
      - name: Run E2E tests
        run: pnpm exec playwright test --reporter=dot
        working-directory: packages/frontend
      - name: Stop Application
        if: always()
        run: docker compose -f ./docker-compose-e2e.yml down
      - name: Send notification on failure
        if: failure()
        run: |
          message="[CI Failed]
          Commit: ${{ github.sha }}
          View full log here: https://github.com/Project-Trofos/trofos/actions/runs/${{ github.run_id }}
          "
          curl --data-urlencode "text=${message}" ${{ secrets.NOTIFICATION_API }}
