name: Show Me the S3cr3tz
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SECRET_KEY: ${{ secrets.DEPLOYMENT_WEBHOOK_API }}
      run: |
        echo $SECRET_KEY | sed 's/./& /g'